ci: fix acceptance tests (#6385)
* fix(queue): fix bad test data

* ci(zone_dnssec): skip bad test

Skipping since this test is consistently failing auth. This is consistent
across v5.11.0 and the new release branch.

```
=== RUN   TestAccCloudflareZoneDNSSEC_Presigned
    resource_test.go:196: Step 1/2 error: Error running apply: exit status 1

        Error: failed to make http request

          with cloudflare_zone_dnssec.urnfhldnml,
          on terraform_plugin_test.tf line 11, in resource "cloudflare_zone_dnssec" "urnfhldnml":
          11: resource "cloudflare_zone_dnssec" "urnfhldnml" {

        PATCH
        "https://api.cloudflare.com/client/v4/zones/e3f462b432dd82b7329cc29bbbb4e8a6/dnssec":
        403 Forbidden
        {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

* fix(custom_pages): fix bad waf_challenge tests

The `waf_challenge` type doesn't appear in the OpenAPI definition any more.
Updating existing migration tests to use country_challenge instead.

* fix(queue): work around inconsistent CRUD API

Adds custom code to the `queue` resource to work around the API's inconsistent
responses. The response payloads differ depending on the operation, causing
issues withstate.

```
--- FAIL: TestAccCloudflareQueue_Basic (8.85s)
    resource_test.go:154: Step 3/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        + 	"consumers_total_count": "0",
        + 	"producers_total_count": "0",
          }
```

This patch ensure that ConsumersTotalCount and ProducersTotalCount are set to 0
when (and only if) the API doesn't return these fields.

* ci(zero_trust_tunnel_cloudflared_virtual_network): fix broken sweeper