Update TestAccCloudflareRecord_Basic metadata count
The metadata count has increased to 4 so we need to update our assertion of the field.

```
------- Stdout: -------
=== RUN   TestAccCloudflareRecord_Basic
=== PAUSE TestAccCloudflareRecord_Basic
=== CONT  TestAccCloudflareRecord_Basic
--- FAIL: TestAccCloudflareRecord_Basic (1.35s)
testing.go:684: Step 0 error: Check failed: Check 11/12 error: cloudflare_record.foobar: Attribute 'metadata.%' expected "3", got "4"
FAIL
```