test/load_balancer: Swap to using consistent random name generator
Terraform 0.12 requires that resource names don't start with a number
(although they can still contain a number). To ensure we use a
consistent supported format, I've introduced
`generateRandomResourceName` which will be available to all tests for
use whenever a random resource name is required.

Fixes the following CI exception.

```
------- Stdout: -------
=== RUN   TestAccCloudflareLoadBalancerPool_CreateAfterManualDestroy
=== PAUSE TestAccCloudflareLoadBalancerPool_CreateAfterManualDestroy
=== CONT  TestAccCloudflareLoadBalancerPool_CreateAfterManualDestroy
--- FAIL: TestAccCloudflareLoadBalancerPool_CreateAfterManualDestroy (0.00s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test154368520/main.tf:2,42-54: Invalid resource name; A name must start with a letter and may contain only letters, digits, underscores, and dashes.
FAIL
```