Don't use API tokens for healthchecks
The healthcheck service doesn't support API tokens yet so we'll use the
API key + API email authentication instead.

```
------- Stdout: -------
=== RUN   TestAccCloudflareHealthcheckHTTPExists
=== PAUSE TestAccCloudflareHealthcheckHTTPExists
=== CONT  TestAccCloudflareHealthcheckHTTPExists
--- FAIL: TestAccCloudflareHealthcheckHTTPExists (7.47s)
testing.go:683: Step 0 error: errors during apply:
Error: error creating standalone healthcheck: error from makeRequest: HTTP status 501: content "{\"success\":false,\"errors\":[{\"code\":10000,\"message\":\"API Tokens are not supported by this API for now\"}]}\n"
on /opt/teamcity-agent/temp/buildTmp/tf-test132039242/main.tf line 2:
(source code not available)
FAIL
```