fix(ruleset): skip invalid test
Mirage and the Disable Apps feature are currently deprecated, but it looks like
they've been partially EOL'd.

```
--- FAIL: TestAccCloudflareRuleset_SetConfigRules (10.45s)
ruleset_test.go:6489: Step 2/4 error: Error running apply: exit status 1

    Error: failed to make http request

      with cloudflare_ruleset.my_ruleset,
      on 2.tf line 3, in resource "cloudflare_ruleset" "my_ruleset":
       3: resource "cloudflare_ruleset" "my_ruleset" {

    PUT
    "https://api.cloudflare.com/client/v4/zones/0da42c8d2132a9ddaf714f9e7c920711/rulesets/b42c166fd6b34f54996fb6e4e093c6cd":
    400 Bad Request {
      "result": null,
      "success": false,
      "errors": [
        {
          "code": 20251,
          "message": "disable_apps is deprecated",
          "source": {
            "pointer": "/rules/0/action_parameters/disable_apps"
          }
        },
        {
          "code": 20252,
          "message": "mirage has been deprecated and will be ignored",
          "source": {
            "pointer": "/rules/0/action_parameters/mirage"
          }
        }
      ],
      "messages": []
    }
```