ci(zone_dnssec): skip bad test
Skipping since this test is consistently failing auth. This is consistent
across v5.11.0 and the new release branch.

```
=== RUN   TestAccCloudflareZoneDNSSEC_Presigned
    resource_test.go:196: Step 1/2 error: Error running apply: exit status 1

        Error: failed to make http request

          with cloudflare_zone_dnssec.urnfhldnml,
          on terraform_plugin_test.tf line 11, in resource "cloudflare_zone_dnssec" "urnfhldnml":
          11: resource "cloudflare_zone_dnssec" "urnfhldnml" {

        PATCH
        "https://api.cloudflare.com/client/v4/zones/e3f462b432dd82b7329cc29bbbb4e8a6/dnssec":
        403 Forbidden
        {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```