release: 5.8.0 (#5761)
* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* Bump 'terraform-plugin-testing' module and add refresh plan debug helper

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* feat(workers_script): add support for `content_type` attribute (necessary for Python Workers)

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* feat(api): api update

* feat(api): api update

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* DS-15222: Add acceptance tests for logpush_job resource

This adds acceptance tests for `logpush_job` resource, following https://wiki.cfdata.org/display/API/Terraform+Acceptance+Tests

To run test:
```
export CLOUDFLARE_ACCOUNT_ID=a67e14daa5f8dceeb91fe5449ba496eb
export TF_ACC=2721447

export CLOUDFLARE_EMAIL=
export CLOUDFLARE_API_KEY=

go test ./internal/services/logpush_job -run "^TestAccCloudflareLogpushJob_" -v -count 1
```

Notable manual changes on `schema.go` and `model.go` are the following:
 1. Add validators to `max_upload_*` fields, as SDK generator doesn't them under `anyOf` multiple definitions.
 2. Add `no_refresh` attribute for the fields that cause "drift" due to Logpush API json `omitempty`.

* test: initial zone_subscription acceptance tests (#227)

* fix: initial snippets acceptance tests

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* Fix zero_trust_organization resource drift & add import fn

* codegen metadata

* codegen metadata

* Fix zero_trust_access_organization service_auth_401_redirect

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* chore(api): upload stainless config from cloudflare-config

* codegen metadata

* codegen metadata

* codegen metadata

* chore(tests): Add acceptance tests for WARP Connector resource

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* Fix zero_trust_access_policy showing permanent diffs on some toggle attributes

* feat(api): api update

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* feat(api): api update

* codegen metadata

* codegen metadata

* DS-15269: Add no_refresh to NotificationPolicyWebhooksModel.Secret field

This adds `no_refresh` to `NotificationPolicyWebhooksModel.Secret` field, otherwise the plan is failing due to:

    $ go test ./internal/services/notification_policy_webhooks -run "^TestAccCloudflareNotificationPolicyWebhooks_Basic$" -v -count 1

    === RUN   TestAccCloudflareNotificationPolicyWebhooks_Basic
        resource_test.go:26: Step 1/2 error: After applying this test step, the refresh plan was not empty.
            stdout

            Terraform used the selected providers to generate the following execution
            plan. Resource actions are indicated with the following symbols:
              ~ update in-place

            Terraform will perform the following actions:

              # cloudflare_notification_policy_webhooks.eobztushwl will be updated in-place
              ~ resource "cloudflare_notification_policy_webhooks" "eobztushwl" {
                  ~ created_at   = "2025-07-25T18:28:36Z" -> (known after apply)
                    id           = "ac5004182ecc4ab3b665c4b3a46264b2"
                  + last_failure = (known after apply)
                  + last_success = (known after apply)
                    name         = "my webhooks destination for notifications"
                  + secret       = (sensitive value)
                  ~ type         = "generic" -> (known after apply)
                    # (2 unchanged attributes hidden)
                }

            Plan: 0 to add, 1 to change, 0 to destroy.

The acceptance test passes after this change, with temporarily updating `cloudflare-go/v4` vendor package, as described in https://github.com/cloudflare/terraform-provider-cloudflare/commit/061d5b4a8ec30602468cdf71e2501ed0189e63ad

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* test: improved zone acceptance test coverage (#251)

* Added import verification and a few extra checks to existing tests
* Ported some Unicode-related tests from v4 provider
* Moved subscription-related tests from zone to zone_subscription
* Added test of toggling "paused" attribute
* Miscellaneous cleanup

* test: acceptance tests w/ customized pages for each custom_pages identifier

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* feat: state migration for custom_pages

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* fix: add version back to extended email settings for gateway

* codegen metadata

* codegen metadata

* codegen metadata

* chore(workers_script): add import verification step to test cases

* Get `cloudflare_snippets` resource working

* Update schema to support multiple files and to include the name of
  each file.

* Fix multipart uploading of files by using the correct form field name,
  file name, and content type.

* Use the get content endpoint to fetch the snippet's files and
  metadata when refreshing state.

* Mark the created on attribute as `UseStateForUnknown` to prevent plan
  drift.

* Update `apiform` to not marshal computed attributes. This matches the
  behavior of `apijson`, and prevents the snippet's created on and
  modified on attributes being sent in update requests.

* codegen metadata

* codegen metadata

* codegen metadata

* feat(api): api update

* codegen metadata

* Fix zero_trust_access_identity_provider validation for onetimepin & scim_config conflict

* codegen metadata

* codegen metadata

* feat(api): api update

* chore(workers_script): update tests to replace legacy check functions with state checks

* chore: missing import

* Implemented custom model and schema for MCONN

- removed fields that are informational only and are constantly changing
- set the correct plan modifier for the device field
- add compute_optional for a number of schema fields
- add new acceptance test

* Remove WriteOnly flag from zero_trust_access_identity_provider config.client_secret attribute

* Fix zero_trust_access_application constant diffs for warp type apps

* feat(api): api update

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* chore(api): upload OpenAPI schema from api-schemas

* fix: make gateway settings host selector + inspection optional

* chore(api): update composite API spec

* feat(api): api update

* feat(api): api update

* feat(api): api update

* fix(zero_trust_gateway_settings): remove leftover import

* codegen metadata

* codegen metadata

* codegen metadata

* chore(api): upload stainless config from cloudflare-config

* codegen metadata

* chore(api): upload stainless config from cloudflare-config

* codegen metadata

* codegen metadata

* codegen metadata

* codegen metadata

* Revert "Get `cloudflare_snippets` resource working"

* chore(api): upload stainless config from cloudflare-config

* chore(api): upload stainless config from cloudflare-config

* chore: housekeeping

* chore: remove redundant newline

* fix: list item model

* release: 5.8.0

---------

Co-authored-by: stainless-app[bot] <142633134+stainless-app[bot]@users.noreply.github.com>
Co-authored-by: Musa Jundi <musa@cloudflare.com>
Co-authored-by: Vaishak Dinesh <vaishakpdinesh@gmail.com>
Co-authored-by: Cina Saffary <cina@cloudflare.com>
Co-authored-by: Sohei Gallagher <sohei@cloudflare.com>
Co-authored-by: nlsandler <nora@stainless.com>
Co-authored-by: Eduardo Gomes <technikome@gmail.com>
Co-authored-by: Michael Girouard <206137+mgirouard@users.noreply.github.com>
Co-authored-by: João "Pisco" Fernandes <joaocarlos@cloudflare.com>
Co-authored-by: Rex Scaria <arunrex@cloudflare.com>
Co-authored-by: Zak Cutner <zak@cloudflare.com>
Co-authored-by: Vaishak Dinesh <vaishak@cloudflare.com>
Co-authored-by: yihuaf <yihuaf@cloudflare.com>
Co-authored-by: Mike Girouard <mgirouard@cloudflare.com>
Co-authored-by: Zak Cutner <me@zakcutner.com>