test/access_service_tokens: Don't try to use API tokens
The Access Service Tokens endpoints unfortunately don't support API
tokens (the default authentication mechanism used in the tests) so we
need to unset it during test runs until this is resolved. It throws a
very confusing "insufficient permissions" exception.

```
=== RUN   TestAccAccessServiceTokenCreate
--- FAIL: TestAccAccessServiceTokenCreate (0.56s)
    testing.go:569: Step 0 error: errors during apply:

        Error: error creating access service token: error from makeRequest: HTTP status 403: insufficient permissions

          on /opt/teamcity-agent/temp/buildTmp/tf-test595601124/main.tf line 2:
          (source code not available)

FAIL
```