ci: fix acceptance tests (round 2) (#6390)
* fix(queue): fix bad testdata

Fixes invalid testdata for queues.

```
--- FAIL: TestAccCloudflareQueue_Settings_UpdateRetention (3.85s)
resource_test.go:60: Step 1/2 error: Error running apply: exit status 1

    Error: failed to make http request

      with cloudflare_queue.qnwlkvehqj,
      on terraform_plugin_test.tf line 11, in resource "cloudflare_queue" "qnwlkvehqj":
      11: resource "cloudflare_queue" "qnwlkvehqj" {

    POST
    "https://api.cloudflare.com/client/v4/accounts/f037e56e89293a057740de681ac9abbe/queues":
    400 Bad Request {
      "result": null,
      "success": false,
      "errors": [
        {
          "code": 100128,
          "message": "Queue 'qnwlkvehqj' has invalid settings: message_retention_period must be between 60 and 1209600 seconds."
        }
      ],
      "messages": []
    }
```

* ci(queue): skip TestAccCloudflareQueue_Settings_UpdateDeliveryPaused

Skips the `TestAccCloudflareQueue_Settings_UpdateDeliveryPaused` test for now
until the API changes can make their way through codegen.

```
--- FAIL: TestAccCloudflareQueue_Settings_UpdateDeliveryPaused (8.85s)
resource_test.go:29: Step 2/2 error: After applying this test step, the refresh plan was not empty.
    stdout

    Terraform used the selected providers to generate the following execution
    plan. Resource actions are indicated with the following symbols:
      ~ update in-place

    Terraform will perform the following actions:

      # cloudflare_queue.tdcolxmjmr will be updated in-place
      ~ resource "cloudflare_queue" "tdcolxmjmr" {
          ~ consumers             = [] -> (known after apply)
          ~ consumers_total_count = 0 -> (known after apply)
          ~ created_on            = "2025-10-29T20:40:33.662817Z" -> (known after apply)
            id                    = "99f0751ecf114c38a90a8cebce0a0ff5"
          ~ modified_on           = "2025-10-29T20:40:36.647573Z" -> (known after apply)
          ~ producers             = [] -> (known after apply)
          ~ producers_total_count = 0 -> (known after apply)
          ~ settings              = {
              ~ delivery_delay           = 0 -> (known after apply)
              + delivery_paused          = true
              ~ message_retention_period = 345600 -> (known after apply)
            }
            # (3 unchanged attributes hidden)
        }
```

Root cause is that the API doesn't return `delivery_paused` in the response following the PUT request:

```
PUT /client/v4/accounts/f037e56e89293a057740de681ac9abbe/queues/3323539e98874020bf94c14ff44fd961
{
    "queue_name": "smyqtafgoi",
    "settings": {
        "delivery_paused": true
    }
}
```

```
HTTP 200
{
    "errors": [],
    "messages": [],
    "result": {
        "created_on": "2025-10-29T22:38:19.234751Z",
        "modified_on": "2025-10-29T22:38:22.327117Z",
        "queue_id": "3323539e98874020bf94c14ff44fd961",
        "queue_name": "smyqtafgoi",
        "settings": {
            "delivery_delay": 0,
            "message_retention_period": 345600
        }
    },
    "success": true
}
```

* fix(ruleset): skip invalid test

Mirage and the Disable Apps feature are currently deprecated, but it looks like
they've been partially EOL'd.

```
--- FAIL: TestAccCloudflareRuleset_SetConfigRules (10.45s)
ruleset_test.go:6489: Step 2/4 error: Error running apply: exit status 1

    Error: failed to make http request

      with cloudflare_ruleset.my_ruleset,
      on 2.tf line 3, in resource "cloudflare_ruleset" "my_ruleset":
       3: resource "cloudflare_ruleset" "my_ruleset" {

    PUT
    "https://api.cloudflare.com/client/v4/zones/0da42c8d2132a9ddaf714f9e7c920711/rulesets/b42c166fd6b34f54996fb6e4e093c6cd":
    400 Bad Request {
      "result": null,
      "success": false,
      "errors": [
        {
          "code": 20251,
          "message": "disable_apps is deprecated",
          "source": {
            "pointer": "/rules/0/action_parameters/disable_apps"
          }
        },
        {
          "code": 20252,
          "message": "mirage has been deprecated and will be ignored",
          "source": {
            "pointer": "/rules/0/action_parameters/mirage"
          }
        }
      ],
      "messages": []
    }
```