resource/cloudflare_load_balancer: Make steering_policy computed
 - This avoid spurious diffs of this resource when `steering_policy` is not defined in config
   as demonstrated by this failing test:

```
--- FAIL: TestAccCloudflareLoadBalancer_CreateAfterManualDestroy (4.08s)
    testing.go:527: Step 1 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: cloudflare_load_balancer.vmc92sw22l
          steering_policy: "off" => ""
```

 - We cannot set `Default` for this field because default value varies
   based on other settings (per API docs)