ci(queue): skip TestAccCloudflareQueue_Settings_UpdateDeliveryPaused
Skips the `TestAccCloudflareQueue_Settings_UpdateDeliveryPaused` test for now
until the API changes can make their way through codegen.

```
--- FAIL: TestAccCloudflareQueue_Settings_UpdateDeliveryPaused (8.85s)
resource_test.go:29: Step 2/2 error: After applying this test step, the refresh plan was not empty.
    stdout

    Terraform used the selected providers to generate the following execution
    plan. Resource actions are indicated with the following symbols:
      ~ update in-place

    Terraform will perform the following actions:

      # cloudflare_queue.tdcolxmjmr will be updated in-place
      ~ resource "cloudflare_queue" "tdcolxmjmr" {
          ~ consumers             = [] -> (known after apply)
          ~ consumers_total_count = 0 -> (known after apply)
          ~ created_on            = "2025-10-29T20:40:33.662817Z" -> (known after apply)
            id                    = "99f0751ecf114c38a90a8cebce0a0ff5"
          ~ modified_on           = "2025-10-29T20:40:36.647573Z" -> (known after apply)
          ~ producers             = [] -> (known after apply)
          ~ producers_total_count = 0 -> (known after apply)
          ~ settings              = {
              ~ delivery_delay           = 0 -> (known after apply)
              + delivery_paused          = true
              ~ message_retention_period = 345600 -> (known after apply)
            }
            # (3 unchanged attributes hidden)
        }
```

Root cause is that the API doesn't return `delivery_paused` in the response following the PUT request:

```
PUT /client/v4/accounts/f037e56e89293a057740de681ac9abbe/queues/3323539e98874020bf94c14ff44fd961
{
    "queue_name": "smyqtafgoi",
    "settings": {
        "delivery_paused": true
    }
}
```

```
HTTP 200
{
    "errors": [],
    "messages": [],
    "result": {
        "created_on": "2025-10-29T22:38:19.234751Z",
        "modified_on": "2025-10-29T22:38:22.327117Z",
        "queue_id": "3323539e98874020bf94c14ff44fd961",
        "queue_name": "smyqtafgoi",
        "settings": {
            "delivery_delay": 0,
            "message_retention_period": 345600
        }
    },
    "success": true
}
```