Update asserted TestAccCloudflareRecord_LOC string
This value in the API response has changed so we need to update our tests.

Fixes the following:

````
------- Stdout: -------
=== RUN   TestAccCloudflareRecord_LOC
=== PAUSE TestAccCloudflareRecord_LOC
=== CONT  TestAccCloudflareRecord_LOC
--- FAIL: TestAccCloudflareRecord_LOC (4.26s)
testing.go:684: Step 0 error: Check failed: Check 2/4 error: cloudflare_record.foobar: Attribute 'value' expected "37 46 46.000 N 122 23 35.000 W 0.00m 100.00m 0.00m 0.00m", got "37 46 46 N 122 23 35 W 0 100 0 0"
FAIL
```