fix(queue): work around inconsistent CRUD API
Adds custom code to the `queue` resource to work around the API's inconsistent
responses. The response payloads differ depending on the operation, causing
issues withstate.

```
--- FAIL: TestAccCloudflareQueue_Basic (8.85s)
    resource_test.go:154: Step 3/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        + 	"consumers_total_count": "0",
        + 	"producers_total_count": "0",
          }
```

This patch ensure that ConsumersTotalCount and ProducersTotalCount are set to 0
when (and only if) the API doesn't return these fields.